### PR TITLE
avoiding "-" in RMF model to make "aird" file work properly.

### PR DESCRIPTION
**Pull request by jadelkhoury**
I was working on explaing this problem to the Sirius community, and found the odd encoding of "-" in the aird-file. 
Renaming the EMF model, plus manually editing/reparing the aird-file seems to fix this problem.

@jamsden Do the models look as expected now?

### CODE REVIEW

**Comment by jadelkhoury** [comment]
This pull request overrides https://github.com/OSLC/iotp-adaptor/pull/7

**Comment by jamsden** [comment]
Jad, that explains why the old iotp-adaptor diagrams didn't load (I guess), but doesn't explain why it is possible to create new diagrams of the model elements using the same name.

**Comment by jadelkhoury** [comment]
I think it does. 
To start with, there is no problem with a "-" in the EMF file. 

The new aird file simply has `href="iotp-adaptor.toolchain#//@specification"`. and this works fine with the new Sirius code.

The old aird file was instead doing  `href="IoTP%20Adapter.toolchain#//@specification"/>`. I assume old Sirius was encoding.

Now new Sirius no longer encodes (as we can prove given the new aird file). This makes it however fail when it tries to find `IoTP%20Adapter.toolchain`.

**Comment by jamsden** [comment]
Perfect, I'll restore the iotp-adaptor files and do the rename and manual edits and see if the old diagrams open. Thanks.

**Comment by jadelkhoury** [comment]
👍 This pull request has these manual edits otherwise.

**Comment by berezovskyi** [comment]
%20 is the encoded value of a space, not a dash.

--
/Andrew
(from phone)

On 24 Mar 2020, at 17:57, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


👍 This pull request has these manual edits otherwise.

**Comment by jadelkhoury** [comment]
Ahh of course. This means someone must have renamed the EMF file, changing from “ “ to “-“. Breaking  the aird file in the process. 
So this is not really due to a change in Sirius. 

@jamsden! The least intrusive fix is to simply rename the EMF file to have a space instead of “-“. This way you don’t have to change anything else.

**Comment by jamsden** [comment]
Jad,
See: 
I discarded all my changes, pulled master and renamed 
iotp-adaptor.toolchain to "iotp adaptor.toolchain". But you can see from 
above there are no representations in the toolchain model before or after 
the rename.

I see the representations in representation.aird, but you told me not to 
open them from there.


--
Jim Amsden, Senior Technical Staff Member
ELM Quality Manager
919-525-6575

**Comment by jadelkhoury** [comment]
@Jim! Ok, it seems the change was not simply replacing "-" with a " ". There were more subtle changes.

Replace the file name to be "IoTP Adapter.toolchain". 
* Capitalisation was changed.
* Adapter instead of Adaptor.

I can do the pull-request for you too, but thought it good if you experience the change yourself.

**Comment by jamsden** [comment]
Ok, that worked. But I still don't see the diagrams under IoTP Adapter.toolchain, I have to access them through the representations.aird element. Is that correct?

**Comment by jadelkhoury** [comment]
That's strange. Are you expanding the "IoTP Adapter.toolchain" file? Do not double click!
Under the "Toolchain IoT Platform" you should see a ToolchainDiagram. See picture below.
If not, try removing the project and importing it again. (I did not have to do that, but just in case).

image

**Comment by jamsden** [comment]
closing and reopening the project fixed it - not an unusual requirement.

**Comment by jadelkhoury** [comment]
Nice! Closing this pull request, but would be good if you can push your change then jim.

**Pull request closed without merging**
